### ISSUE TITLE
add features to mx_states json file

### ISSUE THREAD

**Issue by DPLATA** [DPLATA/mexdata#1]
each state in Mexico should be mapped in the assets directory with its correspondent own unique json file and added to mx_states json file as an individual feature. This should be a pretty straight forward task and the following steps will provide you with a detailed guideline to get it done. You should make the following changes, where appropriate:

1. create a new issue for the state you want to add to the repo by converting task to issue (rightmost icon within the task)
2. wait for someone to assign it to you to start working on it
3. enter [opendata.com](https://data.opendatasoft.com/explore/dataset/georef-mexico-state-millesime%40public/export/?disjunctive.sta_code&disjunctive.sta_name&location=6,28.64239,-112.1814&basemap=jawg.streets) select 2019 record for the state you selected in the left side menu and download in json format
![state selection](https://res.cloudinary.com/dzappyypg/image/upload/v1672441427/other_stuff/github_asset_1.png)
4. add the downloaded feature as a new file with the lowercase state key (three letters next to the name) as file name inside the mx_states directory
5. copy the whole feature and add it in mx_states json file as a new feature and add state_key with the state key (uppercase) and unemployment_percentage with the value assigned for the state in desocupacion_2022 file. Make sure to copy only the "coordinates" and "type" keys into the mx_states file. Follow the structure and if you are not sure how to do it, please ask questions ;)
6. Make sure the state file e.g. cam.json has in it the complete feature not just the "coordinates" and "type" keys. Again, if this is not clear enough ask us questions.
7. open a PR and request a review. Make sure to include the line "Fixes #number_of_your_issue" in the commit message to automatically closing the issue when the PR is merged.

For the following states:

- [x] #3 Aguascalientes AGS 
- [x] #8 Baja California BC
- [x] #9 Baja California Sur BCS
- [x] #10
- [x] #12
- [x] #13
- [x] #2 Ciudad de México CMX
- [x] #11
- [x] #19
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #20
- [x] #21
- [x] #22
- [x] #23
- [x] #25
- [x] #26
- [x] #27
- [x] #28
- [x] #29
- [x] #30
- [x] #31
- [x] #32
- [x] #33
- [x] #34
- [x] #35
- [x] #36
- [x] #4 Yucatán YUC
- [x] #37

**IF YOU HAVE ANY DOUBTS DON'T HESITATE ON POSTING YOUR QUESTIONS**

**Comment by DPLATA** [comment]
cmx #2

**Comment by DPLATA** [comment]
ags #3

**Comment by DPLATA** [comment]
yuc #4

**Comment by DPLATA** [comment]
bc #8

**Comment by DPLATA** [comment]
bcs #9

**Comment by DPLATA** [comment]
resolved in commit a193792177c6eb0501fcaeda3f2dd54365ec831b
